// Streaming service catalog. Logos are project assets; show artwork + blurbs are seeded here.
import netflixLogo from "@/assets/netflix.jpg.asset.json";
import prime_videoLogo from "@/assets/prime-video.jpg.asset.json";
import apple_tvLogo from "@/assets/apple-tv.jpg.asset.json";
import paramount_plusLogo from "@/assets/paramount-plus.jpg.asset.json";
import disney_plusLogo from "@/assets/disney-plus.jpg.asset.json";
import huluLogo from "@/assets/hulu.jpg.asset.json";
import peacockLogo from "@/assets/peacock.jpg.asset.json";
import amc_plusLogo from "@/assets/amc-plus.jpg.asset.json";
import hboLogo from "@/assets/hbo.jpg.asset.json";

export type Service = { slug: string; name: string; color: string; logo: string };
export type Title = { title: string; year: number | null; poster: string; description: string; genres: string[] };

export const SERVICES: Service[] = [
  { slug: "netflix", name: "Netflix", color: "#E50914", logo: netflixLogo.url },
  { slug: "prime-video", name: "Prime Video", color: "#1399FF", logo: prime_videoLogo.url },
  { slug: "apple-tv", name: "Apple TV+", color: "#111114", logo: apple_tvLogo.url },
  { slug: "paramount-plus", name: "Paramount+", color: "#0064FF", logo: paramount_plusLogo.url },
  { slug: "disney-plus", name: "Disney+", color: "#0B3F5C", logo: disney_plusLogo.url },
  { slug: "hulu", name: "Hulu", color: "#0B0B0F", logo: huluLogo.url },
  { slug: "peacock", name: "Peacock", color: "#0B0B0F", logo: peacockLogo.url },
  { slug: "amc-plus", name: "AMC+", color: "#0B0B0F", logo: amc_plusLogo.url },
  { slug: "hbo", name: "HBO / Max", color: "#0B0B0F", logo: hboLogo.url },
];

export const SERVICE_TITLES: Record<string, Title[]> = {
  "netflix": [
    {"title": "Stranger Things", "year": 2016, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/595/1489169.jpg", "description": "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.", "genres": ["Drama", "Horror", "Science-Fiction"]},
    {"title": "Squid Game", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/576/1440521.jpg", "description": "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits \u2014 with deadly high stakes.", "genres": ["Drama", "Thriller", "Mystery"]},
    {"title": "The Witcher", "year": 2019, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/594/1486674.jpg", "description": "Based on the best-selling fantasy series, The Witcher is an epic tale of fate and family. Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts. But when destiny hurtles him toward a powerful sorceress, and a young princes", "genres": ["Drama", "Action", "Fantasy"]},
    {"title": "Wednesday", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/586/1466410.jpg", "description": "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends \u2014 and foes \u2014 at Nevermore Academy.", "genres": ["Comedy", "Mystery", "Supernatural"]},
    {"title": "Dark", "year": 2017, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/504/1262352.jpg", "description": "A family saga with a supernatural twist, Dark is set in a German town in present day where the disappearance of two young children exposes the double lives and fractured relationships among four families.", "genres": ["Drama", "Science-Fiction", "Supernatural"]},
    {"title": "Money Heist", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/430/1076004.jpg", "description": "Thieves overtake the mint of a unified Korea. With hostages trapped inside, the police must stop them \u2014 as well as the shadowy mastermind behind it all.", "genres": ["Drama", "Crime", "Thriller"]},
    {"title": "One Piece", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/617/1543011.jpg", "description": "With his straw hat and ragtag crew, young pirate Monkey D. Luffy goes on an epic voyage for treasure in this live-action adaptation of the popular manga.", "genres": ["Action", "Adventure", "Fantasy"]},
    {"title": "3 Body Problem", "year": 2024, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/507/1268925.jpg", "description": "Across continents and decades, five brilliant friends make earth-shattering discoveries as the laws of science unravel and an existential threat emerges.", "genres": ["Drama", "Science-Fiction", "Thriller"]},
    {"title": "The Crown", "year": 2016, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/632/1580063.jpg", "description": "The Crown tells the inside story of two of the most famous addresses in the world -- Buckingham Palace and 10 Downing Street - and the intrigues, love lives and machinations behind the great events that shaped the second half of the 20th century. Two houses, two courts, one Crown.", "genres": ["Drama", "History"]},
    {"title": "Ozark", "year": 2017, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/398/996611.jpg", "description": "In this dark, dangerous series, a family struggles after moving to an Ozarks resort community when they're thrust into a world of dirty money.", "genres": ["Drama", "Crime", "Thriller"]},
    {"title": "Bridgerton", "year": 2020, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/614/1535959.jpg", "description": "Based on Julia Quinn's best-selling series of novels, Bridgerton is set in the sexy, lavish and competitive world of Regency London high society. From the glittering ballrooms of Mayfair to the aristocratic palaces of Park Lane and beyond, the series unveils a seductive, sumptuous world replete with", "genres": ["Drama", "Romance"]},
    {"title": "Peaky Blinders", "year": 2013, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/48/122213.jpg", "description": "An epic gangster drama set in the lawless streets of 1920s Birmingham.", "genres": ["Drama", "Crime", "History"]},
    {"title": "Black Mirror", "year": 2011, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/564/1411764.jpg", "description": "Over the last ten years, technology has transformed almost every aspect of our lives before we've had time to stop and question it. In every home; on every desk; in every palm - a plasma screen; a monitor; a smartphone--a black mirror of our 21st Century existence. Black Mirror is a contemporary Bri", "genres": ["Drama", "Science-Fiction", "Thriller"]},
    {"title": "Arcane", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/536/1340287.jpg", "description": "Set in utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions \u2014 and the power that will tear them apart.", "genres": ["Action", "Adventure", "Fantasy"]},
    {"title": "The Sandman", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/423/1059631.jpg", "description": "A rich blend of modern myth and dark fantasy in which contemporary fiction, historical drama and legend are seamlessly interwoven, The Sandman follows the people and places affected by Morpheus, the Dream King, as he mends the cosmic \u2014 and human \u2014 mistakes he's made during his vast existence.", "genres": ["Drama", "Fantasy"]},
    {"title": "Lupin", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/603/1507749.jpg", "description": "Inspired by the adventures of Ars\u00e8ne Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family.", "genres": ["Drama", "Adventure", "Crime"]},
  ],
  "prime-video": [
    {"title": "The Boys", "year": 2019, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/619/1547768.jpg", "description": "In a world where superheroes embrace the darker side of their massive celebrity and fame, The Boys centres on a group of vigilantes known informally as \"The Boys,\" who set out to take down corrupt superheroes with no more than blue collar grit and a willingness to fight dirty.", "genres": ["Action", "Fantasy", "Adult"]},
    {"title": "Fallout", "year": 2024, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/599/1499142.jpg", "description": "Based on one of the greatest video game series of all time, Fallout is the story of haves and have nots in a world in which there's almost nothing left to have. 200 years after the apocalypse, a peaceful denizen from a cozy fallout shelter is forced to return to the surface and is shocked to discove", "genres": ["Drama", "Action", "Science-Fiction"]},
    {"title": "The Lord of the Rings: The Rings of Power", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/633/1584401.jpg", "description": "Set thousands of years before the events of The Lord of the Rings, this epic drama follows an ensemble cast of characters, both familiar and new, as they confront the long-feared re-emergence of evil to Middle-earth.", "genres": ["Drama", "Adventure", "Fantasy"]},
    {"title": "Invincible", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/618/1545777.jpg", "description": "Based on the eponymous comic book, Invincible revolves around Mark Grayson, a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his 17th birthday, Mark begins to develop powers of his own and enters into his father's tutelage.", "genres": ["Drama", "Action", "Science-Fiction"]},
    {"title": "Reacher", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/635/1587564.jpg", "description": "Reacher\u00a0follows Jack Reacher, a veteran military police investigator who has just recently entered civilian life. Reacher is a drifter, carrying no phone and the barest of essentials as he travels the country and explores the nation he once served. When Reacher arrives in the small town of Margrave,", "genres": ["Drama", "Action", "Thriller"]},
    {"title": "The Marvelous Mrs. Maisel", "year": 2017, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/456/1141825.jpg", "description": "It's 1958 Manhattan and Miriam \"Midge\" Maisel has everything she's ever wanted - the perfect husband, kids, and Upper West Side apartment. But when her life suddenly takes a turn and Midge must start over, she discovers a previously unknown talent - one that will take her all the way from the comedy", "genres": ["Drama", "Comedy"]},
    {"title": "Jack Ryan", "year": 2018, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/486/1215704.jpg", "description": "Jack Ryan is a drama featuring Tom Clancy's popular hero Jack Ryan billed as a new contemporary take on the character in his prime as a CIA analyst/operative using the novels as source material.", "genres": ["Drama", "Action", "Espionage"]},
    {"title": "The Expanse", "year": 2015, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/445/1114081.jpg", "description": "A thriller set two hundred years in the future, The Expanse follows the case of a missing young woman who brings a hardened detective and a rogue ship's captain together in a race across the solar system to expose the greatest conspiracy in human history.", "genres": ["Science-Fiction", "Thriller", "Mystery"]},
    {"title": "Gen V", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/587/1469203.jpg", "description": "From the world of The Boys comes Gen V, a thrilling new series set at America's only college for superheroes. These gifted students put their moral boundaries to the test, competing for the university's top ranking, and a chance to join The Seven, Vought International's elite superhero team. When th", "genres": ["Comedy", "Action", "Science-Fiction"]},
    {"title": "Upload", "year": 2020, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/586/1466414.jpg", "description": "Upload is a sci-fi sitcom that takes place in the near future, where people who are near death can be \"uploaded\" into a virtual afterlife of their choice. In 2033, secretly romantic Brooklyn-born Nora works customer service for a luxurious virtual reality environment. When handsome L.A. party boy Na", "genres": ["Comedy", "Science-Fiction", "Mystery"]},
    {"title": "Citadel", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/624/1560435.jpg", "description": "Eight years ago, Citadel, an independent global spy agency, was destroyed by a new syndicate, Manticore. With their memories wiped, elite agents Mason Kane and Nadia Sinh barely escaped with their lives. Eight years later, Mason's former colleague, Bernard Orlick, asks for his help to prevent Mantic", "genres": ["Action", "Thriller", "Espionage"]},
    {"title": "The Wheel of Time", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/564/1411765.jpg", "description": "The Wheel of Time is set in a sprawling, epic world where magic exists, but only women can use it safely. Meaning that in this series \u2014 women hold the keys to power. The story follows Moiraine, a member of the shadowy and influential all-female organization called the \u2018Aes Sedai' as she embarks on a", "genres": ["Drama", "Adventure", "Fantasy"]},
  ],
  "apple-tv": [
    {"title": "Silo", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/631/1577677.jpg", "description": "In a ruined and toxic future, thousands live in a giant silo deep underground. After its sheriff breaks a cardinal rule and residents die mysteriously, engineer Juliette starts to uncover shocking secrets and the truth about the silo.", "genres": ["Drama", "Science-Fiction", "Mystery"]},
    {"title": "Severance", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/548/1371406.jpg", "description": "Mark Scout leads a team at Lumon Industries, whose employees have undergone a severance procedure, which surgically divides their memories between their work and personal lives. This daring experiment in \"work-life balance\" is called into question as Mark finds himself at the center of an unraveling", "genres": ["Drama", "Science-Fiction", "Mystery"]},
    {"title": "Ted Lasso", "year": 2020, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/634/1585930.jpg", "description": "Ted Lasso centers on an idealistic \u2014 and clueless \u2014 all-American football coach hired to manage an English football club \u2014 despite having no soccer coaching experience at all.", "genres": ["Drama", "Comedy", "Sports"]},
    {"title": "Foundation", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/573/1433544.jpg", "description": "When revolutionary Dr. Hari Seldon predicts the impending fall of the Empire, he and a band of loyal followers venture to the far reaches of the galaxy to establish The Foundation in an attempt to rebuild and preserve the future of civilization. Enraged by Hari's claims, the ruling Cleons \u2013 a long l", "genres": ["Drama", "Science-Fiction", "Mystery"]},
    {"title": "Slow Horses", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/593/1484384.jpg", "description": "Slow Horses follows the story of a group of British intelligence agents who serve in a dumping ground department of MI5 called Slough House after the big mistakes they've made that resulted in the end of their mainstream careers.This quick-witted spy drama follows a dysfunctional team of MI5 agents\u2014", "genres": ["Drama", "Thriller", "Espionage"]},
    {"title": "Pachinko", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/532/1330795.jpg", "description": "Told in three different languages: Korean, Japanese and English, Pachinko chronicles the hopes and dreams of four generations of a Korean immigrant family.", "genres": ["Drama"]},
    {"title": "For All Mankind", "year": 2019, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/616/1541416.jpg", "description": "Imagine a world where the global space race never ended. This thrilling \"what if\" take on history from Ronald D. Moore (Outlander, Battlestar Galactica) spotlights the high-stakes lives of NASA astronauts and their families.", "genres": ["Drama", "Science-Fiction"]},
    {"title": "The Morning Show", "year": 2019, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/594/1485135.jpg", "description": "Nominated for three Golden Globes\u00ae, this unapologetically candid drama looks at the modern workplace through the lens of the people who help America wake up. Pull back the curtain on early morning TV.", "genres": ["Drama"]},
    {"title": "Shrinking", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/610/1527402.jpg", "description": "Shrinking follows a grieving therapist who starts to break the rules and tell his clients exactly what he thinks. Ignoring his training and ethics, he finds himself making huge, tumultuous changes to people's lives... including his own.", "genres": ["Comedy"]},
    {"title": "Bad Sisters", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/540/1351090.jpg", "description": "Set in the breath-taking coast of Ireland, Bad Sisters follows the lives of the Garvey sisters, who are bound together by the premature death of their parents and a promise to always protect one another. The tight-knit Garvey sisters have always looked out for each other. When their brother-in-law w", "genres": ["Drama", "Comedy", "Thriller"]},
    {"title": "Monarch: Legacy of Monsters", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/612/1530034.jpg", "description": "After surviving Godzilla's attack on San Francisco, Cate is shaken yet again by a shocking secret. Amid monstrous threats, she embarks on a globetrotting adventure to learn the truth about her family\u2014and the mysterious organization known as Monarch.", "genres": ["Action", "Adventure", "Science-Fiction"]},
    {"title": "Dark Matter", "year": 2024, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/633/1584721.jpg", "description": "Hailed as one of the best sci-fi novels of the decade, Dark Matter is a story about the road not taken. The series follows Jason Dessen, a physicist, professor, and family man who \u2013 one night while walking home on the streets of Chicago \u2013 is abducted into an alternate version of his life. Wonder qui", "genres": ["Science-Fiction", "Thriller", "Mystery"]},
  ],
  "paramount-plus": [
    {"title": "Yellowstone", "year": 2018, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/545/1362616.jpg", "description": "Yellowstone follows the Dutton family, led by John Dutton, who controls the largest contiguous ranch in the United States, under constant attack by those it borders \u2014 land developers, an Indian reservation, and America's first National Park. It is an intense study of a violent world far from media s", "genres": ["Drama", "Western"]},
    {"title": "Star Trek: Strange New Worlds", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/635/1589217.jpg", "description": "Star Trek: Strange New Worlds follows Captain Pike, Science Officer Spock and Number One in the decade before Captain Kirk boarded the U.S.S. Enterprise, as they explore new worlds around the galaxy.", "genres": ["Action", "Adventure", "Science-Fiction"]},
    {"title": "Halo", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/502/1256105.jpg", "description": "With the galaxy on the brink of destruction, Master Chief John-117 leads his team of Spartans against the alien threat known as the Covenant.", "genres": ["Action", "Science-Fiction"]},
    {"title": "1923", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/557/1392576.jpg", "description": "1923 focuses on the Dutton family's next two generations as they struggle to survive historic drought, lawlessness and prohibition, and an epidemic of cattle theft; all battled beneath the cloud of Montana's great depression, which preceded the nation by almost a decade.", "genres": ["Drama", "Western"]},
    {"title": "Tulsa King", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/588/1471782.jpg", "description": "Tulsa King follows New York mafia capo Dwight \"The General\" Manfredi, just after he is released from prison after 25 years and unceremoniously exiled by his boss to set up shop in Tulsa, Oklahoma. Realizing that his mob family may not have his best interests in mind, Dwight slowly builds a \"crew\" fr", "genres": ["Drama", "Comedy", "Crime"]},
    {"title": "Landman", "year": 2024, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/598/1495770.jpg", "description": "Set in the proverbial boomtowns of West Texas, Landman is a modern day tale of fortune seeking in the world of oil rigs. The series is an upstairs/downstairs story of roughnecks and wildcat billionaires fueling a boom so big, it's reshaping our climate, our economy and our geopolitics.", "genres": ["Drama"]},
    {"title": "Star Trek: Discovery", "year": 2017, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/504/1260637.jpg", "description": "Star Trek, one of the most iconic and influential global television franchises, returns 50 years after it first premiered, with Star Trek: Discovery. The series will feature a new ship, new characters and new missions, while embracing the same ideology and hope for the future that inspired a generat", "genres": ["Drama", "Adventure", "Science-Fiction"]},
    {"title": "Evil", "year": 2019, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/528/1321353.jpg", "description": "Evil is a psychological mystery that examines the origins of evil along the dividing line between science and religion. The series focuses on a skeptical female psychologist who joins a priest-in-training and a carpenter as they investigate the Church's backlog of unexplained mysteries, including su", "genres": ["Drama", "Thriller", "Supernatural"]},
    {"title": "Mayor of Kingstown", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/594/1486611.jpg", "description": "Mayor of Kingstown is set in a small Michigan town where the only industry remaining are federal, state, and private prisons, the story follows the McLusky family, the power brokers between the police, criminals, inmates, prison guards and politicians, in a city completely dependent on prisons and t", "genres": ["Drama"]},
    {"title": "Special Ops: Lioness", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/635/1587727.jpg", "description": "Lioness, inspired by an actual U.S. Military program, follows the life of Joe while she attempts to balance her personal and professional life as the tip of the CIA's spear in the war on terror. The Lioness Program, overseen by Kaitlyn Meade and Donald Westfield, enlists an aggressive Marine Raider ", "genres": ["Drama", "Thriller", "Espionage"]},
  ],
  "disney-plus": [
    {"title": "The Mandalorian", "year": 2019, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/501/1253498.jpg", "description": "After the stories of Jango and Boba Fett, another warrior emerges in the Star Wars universe. The Mandalorian is set after the fall of the Empire and before the emergence of the First Order. We follow the travails of a lone gunfighter in the outer reaches of the galaxy far from the authority of the N", "genres": ["Action", "Adventure", "Science-Fiction"]},
    {"title": "Loki", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/478/1195717.jpg", "description": "Loki follows the trickster and shape-shifter god who pops up throughout human history as an unlikely influencer on historical events.", "genres": ["Action", "Adventure", "Science-Fiction"]},
    {"title": "Andor", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/564/1411766.jpg", "description": "Andor explores a new perspective from the\u202fStar Wars\u202fgalaxy, focusing on Cassian Andor's journey to discover the difference he can make. The series brings forward the tale of the burgeoning rebellion against the Empire and how people and planets became involved. It's an era filled with danger, decept", "genres": ["Science-Fiction", "Thriller", "Espionage"]},
    {"title": "Ahsoka", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/473/1184972.jpg", "description": "Set after the fall of the Empire, Ahsoka follows the former Jedi knight Ahsoka Tano as she investigates an emerging threat to a vulnerable galaxy.", "genres": ["Action", "Adventure", "Science-Fiction"]},
    {"title": "WandaVision", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/295/738028.jpg", "description": "WandaVision blends the style of classic sitcoms with the Marvel Cinematic Universe in which Wanda Maximoff and Vision\u2014two super-powered beings living their ideal suburban lives\u2014begin to suspect that everything is not as it seems.", "genres": ["Drama", "Comedy", "Science-Fiction"]},
    {"title": "The Bear", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/629/1574642.jpg", "description": "Carmy, a young fine-dining chef, comes home to Chicago to run his family sandwich shop. As he fights to transform the shop and himself, he works alongside a rough-around-the-edges crew that ultimately reveal themselves as his chosen family.", "genres": ["Drama", "Comedy", "Food"]},
    {"title": "Only Murders in the Building", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/586/1466415.jpg", "description": "Only Murders in the Building follows three New Yorkers who find they have a mutual interest in solving true crime \u2013 but limit their amateur sleuthing to only murders in their building.", "genres": ["Comedy", "Crime", "Mystery"]},
    {"title": "Moon Knight", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/407/1019370.jpg", "description": "When Steven Grant, a mild-mannered gift-shop employee, becomes plagued with blackouts and memories of another life, he discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector. As Steven/Marc's enemies converge upon them, they must navigate their complex identiti", "genres": ["Action", "Adventure", "Fantasy"]},
    {"title": "The Falcon and the Winter Soldier", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/295/739854.jpg", "description": "Marvel Studios' The Falcon and The Winter Soldier stars Anthony Mackie as Sam Wilson aka The Falcon, and Sebastian Stan as Bucky Barnes aka The Winter Soldier. The pair, who came together in the final moments of \"Avengers: Endgame,\" team up on a global adventure that tests their abilities\u2014and their ", "genres": ["Drama", "Action", "Science-Fiction"]},
    {"title": "Hawkeye", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/383/959105.jpg", "description": "Marvel Studios' Hawkeye is an original new series set in post-blip New York City where former Avenger Clint Barton aka Hawkeye has a seemingly simple mission: get back to his family for Christmas. But when a threat from his past shows up, Hawkeye reluctantly teams up with Kate Bishop, a 22-year-old ", "genres": ["Drama", "Action", "Adventure"]},
    {"title": "Percy Jackson and the Olympians", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/633/1584337.jpg", "description": "12-year-old modern demigod Percy Jackson has just come to terms with his newfound supernatural powers when the sky god Zeus accuses him of stealing his master lightning bolt. Now Percy must trek across America to find it and restore order to Olympus.", "genres": ["Adventure", "Fantasy", "Supernatural"]},
    {"title": "Shogun", "year": 2024, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/506/1265637.jpg", "description": "Sh\u014dgun is set in Japan in the year 1600 at the dawn of a century-defining civil war. Lord Yoshii Toranaga is fighting for his life as his enemies on the Council of Regents unite against him, when a mysterious European ship is found marooned in a nearby fishing village.", "genres": ["Drama", "Adventure", "History"]},
  ],
  "hulu": [
    {"title": "The Handmaid's Tale", "year": 2017, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/562/1406667.jpg", "description": "The Handmaid's Tale is the story of life in the dystopia of Gilead, a totalitarian society in what was formerly the United States. Facing environmental disasters and a plunging birthrate, Gilead is ruled by a twisted fundamentalism in its militarized \u2018return to traditional values'. As one of the few", "genres": ["Drama", "Science-Fiction"]},
    {"title": "Shogun", "year": 2024, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/506/1265637.jpg", "description": "Sh\u014dgun is set in Japan in the year 1600 at the dawn of a century-defining civil war. Lord Yoshii Toranaga is fighting for his life as his enemies on the Council of Regents unite against him, when a mysterious European ship is found marooned in a nearby fishing village.", "genres": ["Drama", "Adventure", "History"]},
    {"title": "Only Murders in the Building", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/586/1466415.jpg", "description": "Only Murders in the Building follows three New Yorkers who find they have a mutual interest in solving true crime \u2013 but limit their amateur sleuthing to only murders in their building.", "genres": ["Comedy", "Crime", "Mystery"]},
    {"title": "Fargo", "year": 2014, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/487/1219631.jpg", "description": "Fargo is a seasonal anthology crime drama with some dark comical elements, inspired by the film Fargo written by the Coen brothers. Each season follows a new case and new characters, all entrenched in the trademark humor, murder and \"Minnesota nice\" that has made the film an enduring classic.", "genres": ["Drama", "Comedy", "Crime"]},
    {"title": "The Great", "year": 2020, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/460/1151199.jpg", "description": "The Great is a satirical, comedic drama about the rise of Catherine the Great from outsider to the longest reigning female ruler in Russia's history. A fictionalized, fun and anachronistic story of an idealistic, romantic young girl, who arrives in Russia for an arranged marriage to the mercurial Em", "genres": ["Drama", "Comedy", "History"]},
    {"title": "Under the Bridge", "year": 2024, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/592/1480211.jpg", "description": "Limited series based on Rebecca Godfrey's book about the 1997 true story of a fourteen-year-old who went to join friends at a party and never returned home14-year-old Reena Virk joined friends at a party and never returned home. Through the eyes of Godfrey and a local police officer, the series take", "genres": ["Drama", "Crime"]},
    {"title": "Nine Perfect Strangers", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/569/1423326.jpg", "description": "Nine Perfect Strangers takes place at a boutique health-and-wellness resort that promises healing and transformation as nine stressed city dwellers try to get on a path to a better way of living. Watching over them during this ten-day retreat is the resort's director Masha, a woman on a mission to r", "genres": ["Drama", "Thriller", "Mystery"]},
    {"title": "Castle Rock", "year": 2018, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/214/536992.jpg", "description": "A psychological-horror series set in the Stephen King multiverse, Castle Rock combines the mythological scale and intimate character storytelling of King's best-loved works, weaving an epic saga of darkness and light, played out on a few square miles of Maine woodland. The fictional Maine town of Ca", "genres": ["Drama", "Horror", "Thriller"]},
    {"title": "The Dropout", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/395/987963.jpg", "description": "The story of Elizabeth Holmes and Theranos is an unbelievable tale of ambition and fame gone terribly wrong. How did the world's youngest self-made female billionaire lose it all in the blink of an eye? How did the woman once heralded as \u2018the next Steve Jobs' find herself facing criminal charges \u2014 t", "genres": ["Drama"]},
    {"title": "Reservation Dogs", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/475/1189118.jpg", "description": "Reservation Dogs follows four Native teenagers in rural Oklahoma who spend their days committing crime... and fighting it.", "genres": ["Drama", "Comedy"]},
  ],
  "peacock": [
    {"title": "Poker Face", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/567/1419482.jpg", "description": "Poker Face is a \"mystery-of-the-week\" series following Natasha Lyonne's Charlie Cale, who has an extraordinary ability to determine when someone is lying. She hits the road with her Plymouth Barracuda and with every stop encounters a new cast of characters and strange crimes she can't help but solve", "genres": ["Drama", "Crime", "Mystery"]},
    {"title": "The Traitors", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/607/1518729.jpg", "description": "Set in a remote castle in the Scottish Highlands and based on the wildly popular Dutch series of the same name, 5-time Emmy-nominated Alan Cumming plays host to twenty larger-than-life personalities (including reality A-listers and America's best game players) who come together to complete a series ", "genres": []},
    {"title": "Yellowstone", "year": 2018, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/545/1362616.jpg", "description": "Yellowstone follows the Dutton family, led by John Dutton, who controls the largest contiguous ranch in the United States, under constant attack by those it borders \u2014 land developers, an Indian reservation, and America's first National Park. It is an intense study of a violent world far from media s", "genres": ["Drama", "Western"]},
    {"title": "Mrs. Davis", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/452/1132197.jpg", "description": "Mrs. Davis is an exploration of faith versus technology - an epic battle of biblical and binary proportions. \"Mrs. Davis\" is the world's most powerful Artificial Intelligence. Simone is the nun devoted to destroying Her.", "genres": ["Drama", "Comedy", "Science-Fiction"]},
    {"title": "Twisted Metal", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/581/1452707.jpg", "description": "Twisted Metal is about a motor-mouthed outsider offered a chance at a better life, but only if he can successfully deliver a mysterious package across a post-apocalyptic wasteland. With the help of a trigger-happy car thief, he faces savage marauders driving vehicles of destruction and other dangers", "genres": ["Action", "Fantasy", "Science-Fiction"]},
    {"title": "Bel-Air", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/599/1499439.jpg", "description": "Set in modern-day Los Angeles, Bel-Air imagines the beloved sitcom The Fresh Prince of Bel-Air through a new, dramatic take on Will's complicated journey from the streets of West Philadelphia to the gated mansions of Bel-Air. As these two worlds collide, Will reckons with the power of second chances", "genres": ["Drama"]},
    {"title": "Dr. Death", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/490/1225885.jpg", "description": "Dr. Death is an American true crime drama anthology television series created by Patrick Macmanus, based on the podcast of the same name. Season 1 dramatizes the story of Christopher Duntsch, an American neurosurgeon convicted after permanently mutilating his patients, killing two of them. Season 2 ", "genres": ["Drama", "Thriller", "Medical"]},
    {"title": "The Office", "year": 2005, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/481/1204342.jpg", "description": "Steve Carell stars in The Office, a fresh and funny mockumentary-style glimpse into the daily interactions of the eccentric workers at the Dunder Mifflin paper supply company. Based on the smash-hit British series of the same name and adapted for American Television by Greg Daniels, this fast-paced ", "genres": ["Comedy"]},
    {"title": "Based on a True Story", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/542/1356251.jpg", "description": "Based on a True Story is about a realtor, a plumber and a former tennis star whose lives unexpectedly collide, exposing America's obsession with true crime and murder.", "genres": ["Comedy", "Crime", "Thriller"]},
    {"title": "Ted", "year": 2024, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/616/1541133.jpg", "description": "In this comedic prequel event series to the Ted films, it's 1993, and Ted the bear's moment of fame has passed. He's now living back home in Framingham, Massachusetts with his best friend, 16-year-old John Bennett, along with John's parents, Matty and Susan and cousin Blaire. Ted may be a lousy infl", "genres": ["Comedy", "Fantasy"]},
  ],
  "amc-plus": [
    {"title": "The Walking Dead: The Ones Who Live", "year": 2024, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/501/1253558.jpg", "description": "The Walking Dead: The Ones Who Live presents an epic love story of two characters changed by a changed world. Kept apart by distance. By an unstoppable power. By the ghosts of who they were. Rick and Michonne are thrown into another world, built on a war against the dead... And ultimately, a war aga", "genres": ["Drama", "Action", "Horror"]},
    {"title": "Interview with the Vampire", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/469/1173859.jpg", "description": "Based on Anne Rice's iconic and bestselling novel, Anne Rice's Interview with the Vampire follows Louis de Pointe, Lestat de Lioncourt and Claudia's epic story of love, blood and the perils of immortality, as told to the journalist Daniel Molloy. Chafing at the limitations of life as a Black man in ", "genres": ["Horror", "Supernatural"]},
    {"title": "Mayfair Witches", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/548/1371382.jpg", "description": "Anne Rice's Mayfair Witches centers on an intuitive young neurosurgeon who discovers that she is the unlikely heir to a family of witches. As she grapples with her newfound powers, she must contend with a sinister presence that has haunted her family for generations.", "genres": ["Drama", "Fantasy", "Supernatural"]},
    {"title": "Dark Winds", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/613/1534425.jpg", "description": "Based on the iconic Leaphorn & Chee book series by Tony Hillerman, Dark Winds is a psychological thriller that follows two Navajo police officers in the 1970s Southwest, as their search for clues in a grisly double murder case forces them to challenge their own spiritual beliefs and come to terms wi", "genres": ["Crime", "Thriller", "Mystery"]},
    {"title": "The Terror", "year": 2018, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/625/1563397.jpg", "description": "The Terror is an American anthology television series exploring historical speculative fiction based on true events.The series is named after Dan Simmons's 2007 novel, which serves as the basis for the first season and is a fictionalized account of Captain Sir John Franklin's lost expedition to the ", "genres": ["Drama", "Horror", "Thriller"]},
    {"title": "Fear the Walking Dead", "year": 2015, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/479/1198360.jpg", "description": "Living in the same universe as The Walking Dead, Fear the Walking Dead is a gritty drama that explores the onset of the undead apocalypse through the lens of a fractured family. Set in a city where people come to escape, shield secrets, and bury their pasts, a mysterious outbreak threatens to disrup", "genres": ["Drama", "Action", "Horror"]},
    {"title": "Better Call Saul", "year": 2015, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/501/1253515.jpg", "description": "Better Call Saul is the prequel to the award-winning series Breaking Bad, set six years before Saul Goodman became Walter White's lawyer. When we meet him, the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to", "genres": ["Drama", "Crime", "Legal"]},
    {"title": "Killing Eve", "year": 2018, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/397/994197.jpg", "description": "Based on the novellas by Luke Jennings, Killing Eve centers on two women; Eve is a bored, whip-smart, pay-grade security services operative whose desk-bound job doesn't fulfill her fantasies of being a spy. Villanelle is an elegant, talented killer who clings to the luxuries her violent job affords ", "genres": ["Drama", "Crime", "Thriller"]},
    {"title": "The Walking Dead: Daryl Dixon", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/581/1453640.jpg", "description": "The Walking Dead: Daryl Dixon is a spinoff series set in The Walking Dead Universe that centers around the eponymous character. Daryl washes ashore in France, raising the ire of a splintered but growing autocratic movement centered in Paris and endangering a young boy at the heart of a benevolent re", "genres": ["Drama", "Action", "Horror"]},
    {"title": "Orphan Black: Echoes", "year": 2024, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/518/1297076.jpg", "description": "Set in the near future, Orphan Black: Echoes takes a deep dive into the exploration of the scientific manipulation of human existence. It follows a group of women as they weave their way into each other's lives and embark on a journey, unravelling the mystery of their identity and uncovering a story", "genres": ["Drama", "Science-Fiction", "Thriller"]},
  ],
  "hbo": [
    {"title": "The Last of Us", "year": 2023, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/563/1409008.jpg", "description": "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.", "genres": ["Drama", "Action", "Horror"]},
    {"title": "House of the Dragon", "year": 2022, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/627/1568449.jpg", "description": "Set 200 years before the events of Game of Thrones, House of the Dragon tells the history of House Targaryen as they fight through a civil war.", "genres": ["Drama", "Action", "Fantasy"]},
    {"title": "Succession", "year": 2018, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/453/1134275.jpg", "description": "Succession follows the saga of the Roys, a fictional, American global-media family that is not only rich and powerful but also powerfully dysfunctional. The drama will explore family loyalty, international business and the perils of power in the 21st century.Power, politics, money...it's all in the ", "genres": ["Drama", "Family"]},
    {"title": "The White Lotus", "year": 2021, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/557/1393876.jpg", "description": "A social satire set at an exclusive tropical resort, The White Lotus follows the exploits of various guests and employees over the span of a week.", "genres": ["Drama", "Comedy"]},
    {"title": "True Detective", "year": 2014, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/490/1226764.jpg", "description": "Touch darkness and darkness touches you back. True Detective centers on troubled cops and the investigations that drive them to the edge. Each season features a new cast and a new case.True Detective is an American anthology crime drama television series created and written by Nic Pizzolatto.", "genres": ["Drama", "Crime", "Thriller"]},
    {"title": "Game of Thrones", "year": 2011, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/498/1245274.jpg", "description": "Based on the bestselling book series A Song of Ice and Fire by George R.R. Martin, this sprawling new HBO drama is set in a world where summers span decades and winters can last a lifetime. From the scheming south and the savage eastern lands, to the frozen north and ancient Wall that protects the r", "genres": ["Drama", "Adventure", "Fantasy"]},
    {"title": "Chernobyl", "year": 2019, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/193/482599.jpg", "description": "Chernobyl dramatizes the true story of one of the worst man-made catastrophes in history and tells of the brave men and women who sacrificed to save Europe from unimaginable disaster. The miniseries focuses on the heartbreaking scope of the nuclear plant disaster that occurred in Ukraine in April 19", "genres": ["Drama", "History"]},
    {"title": "Euphoria", "year": 2019, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/621/1552657.jpg", "description": "Euphoria follows a group of high school students as they navigate love and friendships in a world of drugs, sex, trauma, and social media.", "genres": ["Drama", "Crime", "Thriller"]},
    {"title": "The Penguin", "year": 2024, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/536/1340329.jpg", "description": "Starring Colin Farrell as Oz Cobb (aka The Penguin), the DC Studios series continues filmmaker Matt Reeves' The Batman epic crime saga that began with Warner Bros. Pictures' global blockbuster The Batman. Developed by showrunner Lauren LeFranc, the series centers on the character played by Farrell i", "genres": ["Drama", "Crime"]},
    {"title": "Barry", "year": 2018, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/455/1138151.jpg", "description": "Barry is a dark comedy about a depressed, low-rent hitman from the Midwest. Lonely and dissatisfied in his life, he reluctantly travels to Los Angeles to execute a hit on an aspiring actor. Barry follows his \"mark\" into an acting class and ends up finding an accepting community in a group of eager h", "genres": ["Drama", "Comedy", "Crime"]},
    {"title": "Westworld", "year": 2016, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/445/1113927.jpg", "description": "Westworld is a dark odyssey about the dawn of artificial consciousness and the evolution of sin. Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or depraved, can be indulged.", "genres": ["Drama", "Science-Fiction", "Western"]},
    {"title": "Watchmen", "year": 2019, "poster": "https://static.tvmaze.com/uploads/images/original_untouched/212/530211.jpg", "description": "Based on the DC Comic graphic novel, Watchmen is an alternative history series following a group of costumed crimefighters investigating the murder of one of their own.", "genres": ["Drama", "Action", "Science-Fiction"]},
  ],
};

export function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

export function findService(slug: string) {
  return SERVICES.find((s) => s.slug === slug);
}

export function findTitle(service: string, titleSlug: string) {
  return (SERVICE_TITLES[service] ?? []).find((t) => slugify(t.title) === titleSlug);
}
