/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as UniversesRouteImport } from './routes/universes'
import { Route as TheoriesRouteImport } from './routes/theories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ContinueRouteImport } from './routes/continue'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as WatchServiceRouteImport } from './routes/watch.$service'
import { Route as StoriesIdRouteImport } from './routes/stories.$id'
import { Route as OnboardingUsernameRouteImport } from './routes/onboarding.username'
import { Route as FeedPostIdRouteImport } from './routes/feed.$postId'
import { Route as CommunitySalemRouteImport } from './routes/community.salem'
import { Route as CommunitySlugRouteImport } from './routes/community.$slug'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedBooksRouteImport } from './routes/_authenticated/books'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio.index'
import { Route as WatchServiceTitleRouteImport } from './routes/watch.$service.$title'
import { Route as AuthenticatedStudioProjectIdRouteImport } from './routes/_authenticated/studio.$projectId'
import { Route as WatchServiceTitleSeasonEpisodeRouteImport } from './routes/watch.$service.$title.$season.$episode'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversesRoute = UniversesRouteImport.update({
  id: '/universes',
  path: '/universes',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoriesRoute = TheoriesRouteImport.update({
  id: '/theories',
  path: '/theories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinueRoute = ContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchServiceRoute = WatchServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => WatchRoute,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingUsernameRoute = OnboardingUsernameRouteImport.update({
  id: '/onboarding/username',
  path: '/onboarding/username',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedPostIdRoute = FeedPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => FeedRoute,
} as any)
const CommunitySalemRoute = CommunitySalemRouteImport.update({
  id: '/community/salem',
  path: '/community/salem',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/community/$slug',
  path: '/community/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksRoute = AuthenticatedBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const WatchServiceTitleRoute = WatchServiceTitleRouteImport.update({
  id: '/$title',
  path: '/$title',
  getParentRoute: () => WatchServiceRoute,
} as any)
const AuthenticatedStudioProjectIdRoute =
  AuthenticatedStudioProjectIdRouteImport.update({
    id: '/studio/$projectId',
    path: '/studio/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const WatchServiceTitleSeasonEpisodeRoute =
  WatchServiceTitleSeasonEpisodeRouteImport.update({
    id: '/$season/$episode',
    path: '/$season/$episode',
    getParentRoute: () => WatchServiceTitleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/continue': typeof ContinueRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theories': typeof TheoriesRoute
  '/universes': typeof UniversesRoute
  '/watch': typeof WatchRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/books': typeof AuthenticatedBooksRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/community/salem': typeof CommunitySalemRoute
  '/feed/$postId': typeof FeedPostIdRoute
  '/onboarding/username': typeof OnboardingUsernameRoute
  '/stories/$id': typeof StoriesIdRoute
  '/watch/$service': typeof WatchServiceRouteWithChildren
  '/community/': typeof CommunityIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/watch/$service/$title': typeof WatchServiceTitleRouteWithChildren
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/watch/$service/$title/$season/$episode': typeof WatchServiceTitleSeasonEpisodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/continue': typeof ContinueRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theories': typeof TheoriesRoute
  '/universes': typeof UniversesRoute
  '/watch': typeof WatchRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/books': typeof AuthenticatedBooksRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/community/salem': typeof CommunitySalemRoute
  '/feed/$postId': typeof FeedPostIdRoute
  '/onboarding/username': typeof OnboardingUsernameRoute
  '/stories/$id': typeof StoriesIdRoute
  '/watch/$service': typeof WatchServiceRouteWithChildren
  '/community': typeof CommunityIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/watch/$service/$title': typeof WatchServiceTitleRouteWithChildren
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/watch/$service/$title/$season/$episode': typeof WatchServiceTitleSeasonEpisodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/continue': typeof ContinueRoute
  '/discover': typeof DiscoverRoute
  '/feed': typeof FeedRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theories': typeof TheoriesRoute
  '/universes': typeof UniversesRoute
  '/watch': typeof WatchRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/books': typeof AuthenticatedBooksRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/community/salem': typeof CommunitySalemRoute
  '/feed/$postId': typeof FeedPostIdRoute
  '/onboarding/username': typeof OnboardingUsernameRoute
  '/stories/$id': typeof StoriesIdRoute
  '/watch/$service': typeof WatchServiceRouteWithChildren
  '/community/': typeof CommunityIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/_authenticated/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/watch/$service/$title': typeof WatchServiceTitleRouteWithChildren
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/watch/$service/$title/$season/$episode': typeof WatchServiceTitleSeasonEpisodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/continue'
    | '/discover'
    | '/feed'
    | '/sitemap.xml'
    | '/theories'
    | '/universes'
    | '/watch'
    | '/admin'
    | '/books'
    | '/chats'
    | '/library'
    | '/community/$slug'
    | '/community/salem'
    | '/feed/$postId'
    | '/onboarding/username'
    | '/stories/$id'
    | '/watch/$service'
    | '/community/'
    | '/stories/'
    | '/studio/$projectId'
    | '/watch/$service/$title'
    | '/studio/'
    | '/watch/$service/$title/$season/$episode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/continue'
    | '/discover'
    | '/feed'
    | '/sitemap.xml'
    | '/theories'
    | '/universes'
    | '/watch'
    | '/admin'
    | '/books'
    | '/chats'
    | '/library'
    | '/community/$slug'
    | '/community/salem'
    | '/feed/$postId'
    | '/onboarding/username'
    | '/stories/$id'
    | '/watch/$service'
    | '/community'
    | '/stories'
    | '/studio/$projectId'
    | '/watch/$service/$title'
    | '/studio'
    | '/watch/$service/$title/$season/$episode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/continue'
    | '/discover'
    | '/feed'
    | '/sitemap.xml'
    | '/theories'
    | '/universes'
    | '/watch'
    | '/_authenticated/admin'
    | '/_authenticated/books'
    | '/_authenticated/chats'
    | '/_authenticated/library'
    | '/community/$slug'
    | '/community/salem'
    | '/feed/$postId'
    | '/onboarding/username'
    | '/stories/$id'
    | '/watch/$service'
    | '/community/'
    | '/stories/'
    | '/_authenticated/studio/$projectId'
    | '/watch/$service/$title'
    | '/_authenticated/studio/'
    | '/watch/$service/$title/$season/$episode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContinueRoute: typeof ContinueRoute
  DiscoverRoute: typeof DiscoverRoute
  FeedRoute: typeof FeedRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TheoriesRoute: typeof TheoriesRoute
  UniversesRoute: typeof UniversesRoute
  WatchRoute: typeof WatchRouteWithChildren
  CommunitySlugRoute: typeof CommunitySlugRoute
  CommunitySalemRoute: typeof CommunitySalemRoute
  OnboardingUsernameRoute: typeof OnboardingUsernameRoute
  StoriesIdRoute: typeof StoriesIdRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universes': {
      id: '/universes'
      path: '/universes'
      fullPath: '/universes'
      preLoaderRoute: typeof UniversesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theories': {
      id: '/theories'
      path: '/theories'
      fullPath: '/theories'
      preLoaderRoute: typeof TheoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continue': {
      id: '/continue'
      path: '/continue'
      fullPath: '/continue'
      preLoaderRoute: typeof ContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$service': {
      id: '/watch/$service'
      path: '/$service'
      fullPath: '/watch/$service'
      preLoaderRoute: typeof WatchServiceRouteImport
      parentRoute: typeof WatchRoute
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/username': {
      id: '/onboarding/username'
      path: '/onboarding/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof OnboardingUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$postId': {
      id: '/feed/$postId'
      path: '/$postId'
      fullPath: '/feed/$postId'
      preLoaderRoute: typeof FeedPostIdRouteImport
      parentRoute: typeof FeedRoute
    }
    '/community/salem': {
      id: '/community/salem'
      path: '/community/salem'
      fullPath: '/community/salem'
      preLoaderRoute: typeof CommunitySalemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/community/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books': {
      id: '/_authenticated/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthenticatedBooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/watch/$service/$title': {
      id: '/watch/$service/$title'
      path: '/$title'
      fullPath: '/watch/$service/$title'
      preLoaderRoute: typeof WatchServiceTitleRouteImport
      parentRoute: typeof WatchServiceRoute
    }
    '/_authenticated/studio/$projectId': {
      id: '/_authenticated/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof AuthenticatedStudioProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/watch/$service/$title/$season/$episode': {
      id: '/watch/$service/$title/$season/$episode'
      path: '/$season/$episode'
      fullPath: '/watch/$service/$title/$season/$episode'
      preLoaderRoute: typeof WatchServiceTitleSeasonEpisodeRouteImport
      parentRoute: typeof WatchServiceTitleRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBooksRoute: typeof AuthenticatedBooksRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedStudioProjectIdRoute: typeof AuthenticatedStudioProjectIdRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBooksRoute: AuthenticatedBooksRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedStudioProjectIdRoute: AuthenticatedStudioProjectIdRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface FeedRouteChildren {
  FeedPostIdRoute: typeof FeedPostIdRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedPostIdRoute: FeedPostIdRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

interface WatchServiceTitleRouteChildren {
  WatchServiceTitleSeasonEpisodeRoute: typeof WatchServiceTitleSeasonEpisodeRoute
}

const WatchServiceTitleRouteChildren: WatchServiceTitleRouteChildren = {
  WatchServiceTitleSeasonEpisodeRoute: WatchServiceTitleSeasonEpisodeRoute,
}

const WatchServiceTitleRouteWithChildren =
  WatchServiceTitleRoute._addFileChildren(WatchServiceTitleRouteChildren)

interface WatchServiceRouteChildren {
  WatchServiceTitleRoute: typeof WatchServiceTitleRouteWithChildren
}

const WatchServiceRouteChildren: WatchServiceRouteChildren = {
  WatchServiceTitleRoute: WatchServiceTitleRouteWithChildren,
}

const WatchServiceRouteWithChildren = WatchServiceRoute._addFileChildren(
  WatchServiceRouteChildren,
)

interface WatchRouteChildren {
  WatchServiceRoute: typeof WatchServiceRouteWithChildren
}

const WatchRouteChildren: WatchRouteChildren = {
  WatchServiceRoute: WatchServiceRouteWithChildren,
}

const WatchRouteWithChildren = WatchRoute._addFileChildren(WatchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContinueRoute: ContinueRoute,
  DiscoverRoute: DiscoverRoute,
  FeedRoute: FeedRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TheoriesRoute: TheoriesRoute,
  UniversesRoute: UniversesRoute,
  WatchRoute: WatchRouteWithChildren,
  CommunitySlugRoute: CommunitySlugRoute,
  CommunitySalemRoute: CommunitySalemRoute,
  OnboardingUsernameRoute: OnboardingUsernameRoute,
  StoriesIdRoute: StoriesIdRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
